<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "payroll_transactions".
 *
 * @property int $id
 * @property int $staff_id
 * @property int $departiment_id
 * @property int $designation_id
 * @property float $basic_salary
 * @property float|null $salary_adjustiment_id
 * @property float|null $allowances
 * @property int|null $night_hours
 * @property float|null $night_allowance
 * @property int|null $normal_ot_hours
 * @property int|null $special_ot_hours
 * @property float|null $normal_ot_amount
 * @property float|null $special_ot_amount
 * @property int|null $absent_days
 * @property float|null $absent_amount
 * @property float $total_earnings
 * @property float $nssf
 * @property float $taxable_income
 * @property float $paye
 * @property float|null $loan
 * @property float|null $salary_advance
 * @property float|null $union_contibution
 * @property float $net_salary
 * @property float $wcf
 * @property float $sdl
 * @property float|null $nhif
 * @property float $total
 * @property string $created_at
 * @property string $updated_at
 * @property int $created_by
 */
class PayrollTransactions extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'payroll_transactions';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['staff_id', 'departiment_id', 'designation_id', 'basic_salary', 'total_earnings', 'nssf', 'taxable_income', 'paye', 'net_salary', 'wcf', 'sdl', 'total', 'created_by'], 'required'],
            [['staff_id', 'departiment_id', 'designation_id', 'night_hours', 'normal_ot_hours', 'special_ot_hours', 'absent_days', 'created_by'], 'integer'],
            [['basic_salary', 'salary_adjustiment_id', 'allowances', 'night_allowance', 'normal_ot_amount', 'special_ot_amount', 'absent_amount', 'total_earnings', 'nssf', 'taxable_income', 'paye', 'loan', 'salary_advance', 'union_contibution', 'net_salary', 'wcf', 'sdl', 'nhif', 'total'], 'number'],
            [['created_at', 'updated_at'], 'safe'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'staff_id' => 'Staff ID',
            'departiment_id' => 'Department',
            'designation_id' => 'Designation',
            'basic_salary' => 'Basic Salary',
            'salary_adjustiment_id' => 'Salary Adjustments',
            'allowances' => 'Allowances',
            'night_hours' => 'Night Hours',
            'night_allowance' => 'Night Allowance',
            'normal_ot_hours' => 'Normal OT Hours',
            'special_ot_hours' => 'Special OT Hours',
            'normal_ot_amount' => 'Normal OT Amount',
            'special_ot_amount' => 'Special OT Amount',
            'absent_days' => 'Absent Days',
            'absent_amount' => 'Absent Amount',
            'total_earnings' => 'Total Earnings',
            'nssf' => 'NSSF',
            'taxable_income' => 'Taxable Income',
            'paye' => 'PAYE',
            'loan' => 'Loan',
            'salary_advance' => 'Salary Advance',
            'union_contibution' => 'Union Contribution',
            'net_salary' => 'Net Salary',
            'wcf' => 'WCF',
            'sdl' => 'SDL',
            'nhif' => 'NHIF',
            'total' => 'Total Cost to Employer',
            'created_at' => 'Generated At',
            'updated_at' => 'Updated At',
            'created_by' => 'Generated By',
        ];
    }
}
