<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "payroll".
 *
 * @property int $id
 * @property int $payroll_transaction_id
 * @property string $created_at
 * @property string $status
 * @property int $created_by
 * @property string $updated_at
 */
class Payroll extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'payroll';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['payroll_transaction_id', 'created_by'], 'required'],
            [['payroll_transaction_id', 'created_by'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['status'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'payroll_transaction_id' => 'Payroll Month',
            'created_at' => 'Generated At',
            'status' => 'Status',
            'created_by' => 'Generated By',
            'updated_at' => 'Updated At',
        ];
    }
}
